

   const product=[
    {
      "id": 1,
      "imgUrl": "https://5.imimg.com/data5/TD/KU/MY-51545753/sg-pumpkin-disco-2c-1kg-500x500.png",
      "name": "Pumpkin Disco",
      "packSize": "250 g",
      "price": 20,
      "strikePrice": "37",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Pumpkin Disco are extremely rich in minerals like potassium and copper, making your body and the immune system strong. This tasty and nutritious vegetable ...",
      "info": ""
    },
    {
      "id": 2,
      "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Hong_Kong_Okra_Aug_25_2012.JPG/220px-Hong_Kong_Okra_Aug_25_2012.JPG",
      "name": "Lady's Finger (Bhindi / Okra / Bhendi) / Bhinda,Vendaikk...",
      "packSize": "500 g",
      "price": 12,
      "strikePrice": 28,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Lady's Finger are extremely rich in minerals like potassium and copper, making your body and the immune system strong. This tasty and nutritious vegetable ...",
      "info": "",
     "tag":"best"
    },
    {
      "id": 3,
      "imgUrl": "https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/277432_2200-732x549.jpg",
      "name": "Beetroot",
      "packSize": "500 g",
      "price": 30,
      "strikePrice": "45",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Beetroot are extremely rich in minerals like potassium and copper, making your body and the immune system strong. This tasty and nutritious vegetable ...",
      "info": ""
    },
    {
      "id": 4,
      "imgUrl": "https://images.healthshots.com/healthshots/en/uploads/2022/01/31210911/yam.jpg",
      "name": "Yam (Suran / Elephant Foot)",
      "packSize": "500 g",
      "price": 43,
      "strikePrice": "55",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Yams are perennial herbaceous vines cultivated for the consumption of their starchy tubers in many temperate and tropical regions, especially in West Africa, ..",
      "info": ""
    },
    {
      "id": 5,
      "imgUrl": "https://plantix.net/en/library/assets/custom/crop-images/onion.jpeg",
      "name": "Onion",
      "packSize": "1 kg",
      "price": 11,
      "strikePrice": 24,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "An onion also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium.",
      "info": ""
    },
    {
      "id": 6,
      "imgUrl": "https://m.media-amazon.com/images/I/61yXL70-RaL._SX679_.jpg",
      "name": "Potato / Batata",
      "packSize": "1 kg",
      "price": 29,
      "strikePrice": 32,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable and a fruit native to the Americas. The plant is a perennial in the ...",
      "info": "",
      "tag":"best"
    },
    {
      "id": 7,
      "imgUrl": "https://i0.wp.com/post.greatist.com/wp-content/uploads/sites/2/2020/11/HEADERube-purple-yam-recipe-chowhound-670x448-1.jpg?w=1155&h=1526",
      "name": "Yam Purple (Kandh)",
      "packSize": "250 g",
      "price": 21,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Yams are perennial herbaceous vines cultivated for the consumption of their starchy tubers in many temperate and tropical regions, especially in West Africa, ..",
      "info": ""
    },
    {
      "id": 8,
      "imgUrl": "https://frugivore-storage.s3.amazonaws.com/media/package/img_one/2019-08-28/67_0thsH8R.jpg",
      "name": "Baby Potato",
      "packSize": "500 g",
      "price": 25,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "The potato is a starchy tuber of the plant Solanum tuberosum and is a root vegetable and a fruit native to the Americas. The plant is a perennial in the ...",
      "info": "",
      "tag":"best"
    },
    {
      "id": 9,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0017/9234/4153/products/onion55_500x.jpg?v=1630863613",
      "name": "Onion - Sambhar",
      "packSize": "250 g",
      "price": 24,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 10,
      "imgUrl": "https://images.indianexpress.com/2019/10/Banana-flower_759.jpg",
      "name": "Banana Flower",
      "packSize": "1 Pc",
      "price": 62,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 11,
      "imgUrl": "https://www.hi5mart.com/image/cache/catalog/Vegetables/Brinjal%20Purple-750x750.jpg",
      "name": "Brinjal Bharta",
      "packSize": "500 g",
      "price": 28,
      "strikePrice": 31,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 12,
      "imgUrl": "https://4.imimg.com/data4/VN/UL/MY-937476/capsicum-500x500.jpg",
      "name": "Capsicum (Shimla), Green Shimla Mirchi",
      "packSize": "250 g",
      "price": 26,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Capsicum is a genus of flowering plants in the nightshade family Solanaceae, native to the Americas, cultivated worldwide for their chili pepper or bell ...",
      "info": ""
    },
    {
      "id": 13,
      "imgUrl": "https://rukminim1.flixcart.com/image/416/416/kt8zb0w0/plant-seed/e/l/4/120-high-yield-rare-salad-cucumber-vegetable-seeds-120-seeds-original-imag6mhjnhksgvtc.jpeg?q=70",
      "name": "Cucumber Green Indian / Kheera / Kakdi",
      "packSize": "500 g",
      "price": 31,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "cucumber, (Cucumis sativus), creeping plant of the gourd family (Cucurbitaceae), widely cultivated for its edible fruit. The nutritional value of the cucumber is low, but its delicate flavour makes it popular for salads and",
      "info": ""
    },
    {
      "id": 14,
      "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6f/Cabbage_and_cross_section_on_white.jpg",
      "name": "Cabbage",
      "packSize": "1 pc",
      "price": 28,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Cabbage, comprising several cultivars of Brassica oleracea, is a leafy green, red, or white biennial plant grown as an annual vegetable crop for its dense-leaved heads",
      "info": ""
    },
    {
      "id": 15,
      "imgUrl": "https://blog-images.pharmeasy.in/2022/07/22134631/22.jpg",
      "name": "Bottle Gourd (Dudhi / Lauki)",
      "packSize": "1 pc",
      "price": 22,
      "strikePrice": 27,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 16,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0854/6844/products/Baigan_600x600.jpg?v=1521101346",
      "name": "Brinjal Kateri, Baingan",
      "packSize": "250 g",
      "price": 9,
      "strikePrice": 11,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Buy Organic Brinjal Kateri online at lowest price from bigbasket and get them delivered at your doorstep. Minimum 5% OFF on products.",
      "info": ""
    },
    {
      "id": 17,
      "imgUrl": "https://4.imimg.com/data4/MI/YO/MY-5333565/drumstick-vegetable-500x500.jpg",
      "name": "Drumstick",
      "packSize": "100 g",
      "price": 13,
      "strikePrice": 15,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "Moringa oleifera is a fast-growing, drought-resistant tree of the family Moringaceae, native to the Indian subcontinent",
      "info": ""
    },
    {
      "id": 18,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/l/30000456_10-fresho-cucumber-white.jpg",
      "name": "Cucumber White",
      "packSize": "500 g",
      "price": 25,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "There are several varieties of white cucumber, varying in size and sweetness. White Wonder - otherwise known as Albino, Ivory King, Jack Frost, Landreths White Slicing or the long white is an heirloom variety introduced in 1893. It's known for its clean, cool taste and crunchy texture.",
      "info": ""
    },
    {
      "id": 19,
      "imgUrl": "https://justnature.store/wp-content/uploads/2021/03/black-brinjal-2.jpg",
      "name": "Brinjal Black / Nagpur",
      "packSize": "500 g",
      "price": 22,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 20,
      "imgUrl": "https://trutrade.org/wp-content/uploads/2018/12/IMG_1828.jpg",
      "name": "Ash Gourd (White Pumpkin)",
      "packSize": "500 g",
      "price": 31,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 21,
      "imgUrl": "https://farmveg.in/wp-content/uploads/2021/02/11gawar.jpg",
      "name": "Beans Cluster (Gavar)",
      "packSize": "250 g",
      "price": 26,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 22,
      "imgUrl": "https://seedsnpots.com/wp-content/uploads/2021/08/french-beans.jpg",
      "name": "Beans French",
      "packSize": "500 g",
      "price": 98,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 23,
      "imgUrl": "https://www.dailypioneer.com/uploads/2017/story/images/big/179170_Untitled-13.jpg",
      "name": "Bumper Offer Onion",
      "packSize": "1 kg",
      "price": 24,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 24,
      "imgUrl": "https://static.toiimg.com/thumb/51327325.cms?width=1200&height=900",
      "name": "Sweet Potato",
      "packSize": "500 g",
      "price": 45,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 25,
      "imgUrl": "https://4.imimg.com/data4/PG/BH/MY-23625743/red-tomatoes-250x250.jpg",
      "name": "Tomato (1 Kg)",
      "packSize": "1 kg",
      "price": 91,
      "strikePrice": 93,
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 26,
      "imgUrl": "https://i0.wp.com/foodtrails25.com/wp-content/uploads/2021/07/IMG_0312-1.jpg?resize=720%2C960&ssl=1",
      "name": "Arbi (Colocasia)",
      "packSize": "500 g",
      "price": 35,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 27,
      "imgUrl": "https://m.media-amazon.com/images/I/71S6oQqVa5L._SL1500_.jpg",
      "name": "Carrot Orange (Local)",
      "packSize": "500 g",
      "price": 26,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": "",
      "tag":"best"
    },
    {
      "id": 28,
      "imgUrl": "https://www.tasteofhome.com/wp-content/uploads/2019/05/radish-shutterstock_1010435131.jpg",
      "name": "Radish",
      "packSize": "500 g",
      "price": 41,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": "",
      "tag":"best"
    },
    {
      "id": 29,
      "imgUrl": "https://theleafandclay.com/wp-content/uploads/2020/12/The-Leaf-And-Clay-Cherry-Tomatoes-Seeds.jpg",
      "name": "Tomato - Cherry",
      "packSize": "200 g",
      "price": 97,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": "",
      "tag":"best"
    },
    {
      "id": 30,
      "imgUrl": "https://5.imimg.com/data5/DW/KY/GLADMIN-25336358/pumpkin-green-500x500.png",
      "name": "Pumpkin Green",
      "packSize": "500 g",
      "price": 11,
      "strikePrice": 13,
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 31,
      "imgUrl": "https://www.avtmccormick.com/wp-content/uploads/2019/12/p2.jpg",
      "name": "Sweet Corn Bunch (Bhutta)",
      "packSize": "1 pc",
      "price": 16,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 32,
      "imgUrl": "https://m.media-amazon.com/images/I/91EdPVzD99L._SL1500_.jpg",
      "name": "Cauliflower",
      "packSize": "1 pc",
      "price": 37,
      "strikePrice": 59,
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 33,
      "imgUrl": "http://cdn.shopify.com/s/files/1/1380/2059/products/Bitter-Gourd_84b03abc-d5f8-469f-ae0b-c3d779ece401_grande.jpg?v=1598078384",
      "name": "Bitter Gourd (Karela)",
      "packSize": "500 g",
      "price": 33,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 34,
      "imgUrl": "https://5.imimg.com/data5/OG/OA/KT/SELLER-81389294/pumpkin-red-1000x1000.jpg",
      "name": "Pumpkin Red",
      "packSize": "500 g",
      "price": 18,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 35,
      "imgUrl": "https://mtseedbank.in/wp-content/uploads/2019/12/snake-groud-11-1.jpg",
      "name": "Snake Gourd (Bada Parwal)",
      "packSize": "250 g",
      "price": 19,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 36,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0475/8398/5816/products/1LyX5_iDDeEJMwgIEAFM4xCtksG33PXtk_4531768c-2620-400b-8b74-9974a4c66f25_1125x700.jpg?v=1608550598",
      "name": "Ridge Gourd (Turai) 500 g",
      "packSize": "500 g",
      "price": 50,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 37,
      "imgUrl": "http://dipsdiner.com/dd/wp-content/uploads/2019/05/Ivy-Gourd-tondli-Food-Style.jpg",
      "name": "Tondli",
      "packSize": "500 g",
      "price": 21,
      "strikePrice": 32,
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 38,
      "imgUrl": "https://veggiesvillage.in/wp-content/uploads/2021/09/20200907024609.jpg",
      "name": "Beans Chawli",
      "packSize": "250 g",
      "price": 16,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 39,
      "imgUrl": "https://4.imimg.com/data4/WG/HL/MY-7941396/sponge-gourd-500x500.jpg",
      "name": "Sponge Gourd (Galka)",
      "packSize": "500 g",
      "price": 41,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    
    {
      "id": 41,
      "imgUrl": "https://m.media-amazon.com/images/I/71fcshdy8OS._SL1500_.jpg",
      "name": "Maya Maida 500G",
      "packSize": "500 g",
      "price": 27,
      "strikePrice": 31,
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "dailyVeggies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 42,
      "imgUrl": "https://iranfreshfruit.net/wp-content/uploads/2020/01/button-mushroom.jpg",
      "name": "Mushroom Button",
      "packSize": "1 unit",
      "price": 46,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "(200 g)",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 43,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0294/7527/4827/products/Basilbunchdesktoptiedwithstring2_600x.jpg?v=1594885161",
      "name": "Basil Italian",
      "packSize": "50 g",
      "price": 9,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 44,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/l/40149661_1-fresho-capsicum-yellow.jpg",
      "name": "Capsicum Yellow / Bell Pepper",
      "packSize": "2pcs(250-350g)",
      "price": 130,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 45,
      "imgUrl": "https://healthybuddha.in/image/cache/catalog/redcapsicum-500x515.jpg",
      "name": "Capsicum Red",
      "packSize": "2 Pcs",
      "price": 75,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "(250-300 gms)",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 46,
      "imgUrl": "https://adiyogifarms.com/assets/Images/Product_Image/zucchini_green.jpg",
      "name": "Zucchini Green",
      "packSize": "200-300gm/pc",
      "price": 85,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 47,
      "imgUrl": "https://m.media-amazon.com/images/I/41vJ97IlThL._SX466_.jpg",
      "name": "Zucchini Yellow",
      "packSize": "200-300gm/pc",
      "price": 82,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 48,
      "imgUrl": "http://cdn.shopify.com/s/files/1/0284/2450/products/ICEBERGLETTUCE_1024x.jpg?v=1595658903",
      "name": "Lettuce Iceberg",
      "packSize": "300-550gm",
      "price": 108,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 49,
      "imgUrl": "http://cdn.grofers.com/app/images/products/sliding_image/443552a.jpg?ts=1648018233",
      "name": "Cabbage Red",
      "packSize": "1 pc",
      "price": 44,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "(Approx 500 g)",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 50,
      "imgUrl": "https://images.immediate.co.uk/production/volatile/sites/30/2022/07/Broccoli-78ec54e.jpg",
      "name": "Broccoli",
      "packSize": "(450g-550g)",
      "price": 203,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "exoticVegetables",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 51,
      "imgUrl": "https://img.krishijagran.com/media/41522/download-1.jpg",
      "name": "Betel Leaf - 12 Pcs",
      "packSize": "12 Pcs",
      "price": 39,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 52,
      "imgUrl": "https://www.jiomart.com/images/product/original/590000527/amaranthus-green-per-bunch-approx-200-g-300-g-product-images-o590000527-p590000527-0-202203151615.jpg",
      "name": "Amaranthus Green",
      "packSize": "250 g",
      "price": 38,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 53,
      "imgUrl": "https://i.ndtvimg.com/mt/cooks/2014-11/lemon.jpg",
      "name": "Lemon(100g) / Nimboo / Nibu",
      "packSize": "100g",
      "price": 17,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 54,
      "imgUrl": "https://www.thespruceeats.com/thmb/3Q6y82SBS5ED-T7ft50iMqogz44=/1000x1000/smart/filters:no_upscale()/what-is-ginger-1807768-hero-02-c589bfc0fe5044d29cb930e74d1b6db9.jpg",
      "name": "Ginger / Adrak",
      "packSize": "100 g",
      "price": 12,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 55,
      "imgUrl": "https://www.netmeds.com/images/cms/wysiwyg/blog/2019/06/Curry_leaves_898.jpg",
      "name": "Curry Leaves",
      "packSize": "50 g",
      "price": 12,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 56,
      "imgUrl": "https://gardenerspath.com/wp-content/uploads/2019/12/Bunch-of-Purple-Garlic-Harvested-and-Cleaned.jpg",
      "name": "Garlic Bunch / Lahsun / Vellulipaya",
      "packSize": "100 g",
      "price": 13,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 57,
      "imgUrl": "https://post.healthline.com/wp-content/uploads/2020/08/732x549_Cilantro_Allergy-1-732x549.jpg",
      "name": "Coriander Leaves / Dhania / Kothimbir",
      "packSize": "100 g",
      "price": 17,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 58,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0017/9234/4153/products/methi_d450fc8b-5fec-4fe0-b2de-3bd7f9dd5c25_540x.jpg?v=1602575318",
      "name": "Methi (Fenugreek Leaves)",
      "packSize": "100 g",
      "price": 27,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 59,
      "imgUrl": "https://5.imimg.com/data5/PI/KX/MY-46595757/fresh-spinach-28palak-29-281kg-29-500x500.png",
      "name": "Palak Spinach",
      "packSize": "250 g",
      "price": 24,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 60,
      "imgUrl": "https://static.toiimg.com/photo/msid-85427212/85427212.jpg?215060",
      "name": "Turmeric",
      "packSize": "250g",
      "price": 15,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 61,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/xxl/10000293_14-fresho-amla.jpg",
      "name": "Amla",
      "packSize": "250 g",
      "price": 29,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 62,
      "imgUrl": "https://m.media-amazon.com/images/I/41NeBtJof0L.jpg",
      "name": "Amaranthus Red",
      "packSize": "250 g",
      "price": 33,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 63,
      "imgUrl": "https://images.medicinenet.com/images/article/main_image/what-are-benefits-of-mint-leaves.jpg",
      "name": "Mint Leaves / Pudina",
      "packSize": "100 g",
      "price": 11,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Mints have square stems and opposite aromatic leaves. Many can spread vegetatively by stolons and can be aggressive in gardens. The small flowers are usually pale purple, pink, or white in colour and are arranged in clusters, either forming whorls or crowded together in a terminal spike.",
      "info": ""
    },
    {
      "id": 64,
      "imgUrl": "http://specialtyproduce.com/sppics/297.png",
      "name": "Spring Onion",
      "packSize": "250 g",
      "price": 23,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Also known as scallions or green onions, spring onions are in fact very young onions, harvested before the bulb has had a chance to swell. Both the long, slender green tops and the small white bulb are edible, and are good either raw or cooked. They have a similar flavour to onions, but are much milder",
      "info": ""
    },
    {
      "id": 65,
      "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Taimo_Okinawa.jpg",
      "name": "Colocasia Leaves",
      "packSize": "1 Pc",
      "price": 7,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Description. They are herbaceous perennial plants with a large corm on or just below the ground surface. The leaves are large to very large, 20–150 cm (7.9–59.1 in) long, with a sagittate shape. The elephant's-ear plant gets its name from the leaves, which are shaped like a large ear or shield.",
      "info": ""
    },
    {
      "id": 66,
      "imgUrl": "http://specialtyproduce.com/sppics/320.png",
      "name": "Lemon Grass",
      "packSize": "100 g",
      "price": 12,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Lemongrass, Cymbopogon citratus, is a perennial grass in the family Poaceae grown for its fragrant leaves and stalks which are used as a flavoring. The grass grows in dense clumps and has several stiff stems and slender blade-like leaves which droop towards the tips.",
      "info": ""
    },
    {
      "id": 67,
      "imgUrl": "https://www.jiomart.com/images/product/original/590003533/green-chilli-200-g-product-images-o590003533-p590003533-0-202203150435.jpg",
      "name": "Chillies Green",
      "packSize": "100 g",
      "price": 9,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Green chillies are a common vegetable used in Indian kitchens for their spicy taste. Green chillies are scientifically known as Capsicum frutescens. The spiciness of green chillies comes from a chemical called capsaicin",
      "info": ""
    },
    {
      "id": 68,
      "imgUrl": "https://www.kew.org/sites/default/files/2020-04/Aloe_Vera.jpg",
      "name": "Aloevera",
      "packSize": "1 Pc",
      "price": 10,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Aloe vera is a herb with succulent leaves that are arranged in a rosette. The leaves are grey to green and sometimes have white spots on their surfaces. They have sharp, pinkish spines along their edges and are the source of the colourless gel found in many commercial and medicinal products.",
      "info": ""
    },
    {
      "id": 69,
      "imgUrl": "http://specialtyproduce.com/sppics/12571.png",
      "name": "Banana Stem",
      "packSize": "1 Pc",
      "price": 58,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "vegetables",
      "subCatagory": "herbsLeafies",
      "tooltipText": "",
      "benefits": "",
      "description": "Banana stems vary in size, averaging at least five centimeters in diameter when sold in markets, and are cylindrical to elongated in shape. The outer layer of the stem is a fibrous, green sheath that is inedible and tough to remove.",
      "info": ""
    },
    {
      "id": 70,
      "imgUrl": "https://rukminim1.flixcart.com/image/416/416/k2xmd8w0/ready-meal/c/k/b/750-veg-pulao-combo-of-3-packs-just-2-eat-original-imafhzhgegjbvzfv.jpeg?q=70",
      "name": "Pulao Combo",
      "packSize": "200 g",
      "price": 49,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "cutsPeeled",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 71,
      "imgUrl": "https://m.media-amazon.com/images/I/71nMF1o7X8L._SX522_.jpg",
      "name": "Garlic Peeled",
      "packSize": "100 g",
      "price": 34,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "cutsPeeled",
      "tooltipText": "",
      "benefits": "",
      "description": "A garlic peeler is a kitchen utensil used to take off the skin off the garlic cloves.A closed, hard-walled container, such as a jar or lidded tub or bowl, can be used to peel garlic. ",
      "info": ""
    },
   
    {
      "id": 73,
      "imgUrl": "https://5.imimg.com/data5/SELLER/Default/2020/8/XC/DG/GW/44103168/vegetables-jpg-500x500.jpg",
      "name": "Mixed Capsicum Combo (1 Pc Capsicum Red + 1 Pc Capsicum Yellow)",
      "packSize": "1 unit",
      "price": 103,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "vegetableCombos",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 74,
      "imgUrl": "https://blogs.rdxsports.com/wp-content/uploads/2018/11/photo-1512621776951-a57141f2eefd.jpg",
      "name": "UPVAS Combo (500 gm Sweet Potato + 500 gm Arbi + 1 Kg Potato)",
      "packSize": "1 unit",
      "price": 112,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "vegetableCombos",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 75,
      "imgUrl": "https://www.artfrommytable.com/wp-content/uploads/2017/09/Roasted-Vegetables-Art-From-My-Table-Vertical-4.jpg",
      "name": "Fresh Salad Combo (250G Carrot + 500 G Cucumber)",
      "packSize": "1 unit",
      "price": 44,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "vegetables",
      "subCatagory": "vegetableCombos",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 76,
      "imgUrl": "https://5.imimg.com/data5/XO/YI/MY-9173589/2-500x500.jpg",
      "name": "Dry Dates - 1 Kg (Pack of 5*200 gms)",
      "packSize": "1 kg",
      "price": 330,
      "strikePrice": 460,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "The dates are rich in natural sugar and proteins to keep your muscles strong.The product is a good source of energy, fibre and vitamins.",
      "info": ""
    },
    {
      "id": 77,
      "imgUrl": "https://m.media-amazon.com/images/I/51DB1K6y+5L.jpg",
      "name": "Cashew Tukda 200gms (Pack of 2*100gms)",
      "packSize": "200 g",
      "price": 167,
      "strikePrice": 236,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "SHREEJI ENTERPRISE - Offering Grade: Cashews Tukda, Pack Size (Kg): 10 kg, Loose at Rs 765/kilogram in Vadodara, Gujarat. Also find Split Cashew Nut price .",
      "info": ""
    },
    {
      "id": 78,
      "imgUrl": "https://m.media-amazon.com/images/I/61i0R-k4XJL._SL1000_.jpg",
      "name": "Dry Dates - 400gms (Pack of 2*200gms)",
      "packSize": "400 g",
      "price": 135,
      "strikePrice": 184,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "What are Dry Dates? A mouth-watering, sweet-tasting fruit that contains a wonderful balance of fat, sugar, calcium, and iron. Dry dates are also called dry",
      "info": ""
    },
    {
      "id": 79,
      "imgUrl": "https://5.imimg.com/data5/HZ/AB/FX/SELLER-84813594/walnut-kernel-500x500.jpg",
      "name": "Walnut 200gms (Pack of 2*100gms)",
      "packSize": "200 g",
      "price": 335,
      "strikePrice": 478,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "A walnut is the edible seed of a drupe of any tree of the genus Juglans (family Juglandaceae), particularly the Persian or English walnut, Juglans regia.",
      "info": ""
    },
    {
      "id": 80,
      "imgUrl": "https://m.media-amazon.com/images/I/61EW2iOvd6L._SL1000_.jpg",
      "name": "Walnut 500gms (Pack of 5*100gms)",
      "packSize": "500 g",
      "price": 825,
      "strikePrice": 1195,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "A walnut is the edible seed of a drupe of any tree of the genus Juglans (family Juglandaceae), particularly the Persian or English walnut, Juglans regia.",
      "info": ""
    },
    {
      "id": 81,
      "imgUrl": "https://m.media-amazon.com/images/I/71gt1vMnVFS._SL1100_.jpg",
      "name": "Cashew & Kismis Combo Pack (Cashew 100gm + Kismis 200gm)",
      "packSize": "1 unit-300 g",
      "price": 149,
      "strikePrice": 246,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Nutraj Premium Dry Fruits Combo Pack, Cashews & Raisins 250g Each, Nutritious & Delicious Natural Dried Fruits | Kaju & Kishmish Combo Pack (500g).",
      "info": ""
    },
    {
      "id": 82,
      "imgUrl": "https://www.dmtraders.com/wp-content/uploads/2021/02/premium-quality-pista-600x600.jpg",
      "name": "Pista Salted 200gms (Pack of 2*100gms)",
      "packSize": "200 g",
      "price": 229,
      "strikePrice": 334,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Miltop premium quality salted irani pistachios 500gm. Tasty salted pistachio are high in protein. These pistas can lower blood cholesterol levels and also have .",
      "info": ""
    },
    {
      "id": 83,
      "imgUrl": "https://i0.wp.com/icelandpala.com/wp-content/uploads/2020/06/GOUR203_result.jpg",
      "name": "Pista Salted - 100gms",
      "packSize": "100 g",
      "price": 115,
      "strikePrice": 167,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 84,
      "imgUrl": "https://m.media-amazon.com/images/I/41Ofvj-hwBL.jpg",
      "name": "Kismis - 200 gms",
      "packSize": "200 g",
      "price": 59,
      "strikePrice": 80,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Reduces bad cholesterol in blood and helps regulate Kishmish helps in digestion, reduces acidity and increase immunity. Helps avoiding premature aging and helps",
      "info": ""
    },
    {
      "id": 85,
      "imgUrl": "https://m.media-amazon.com/images/I/51ZCWuukoaL._AC_SY1000_.jpg",
      "name": "Cashew - 100gm",
      "packSize": "100 g",
      "price": 104,
      "strikePrice": 166,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "The cashew tree (Anacardium occidentale) is a tropical evergreen tree in the genus Anacardium that produces the cashew seed and the cashew apple accessory .",
      "info": ""
    },
    {
      "id": 86,
      "imgUrl": "https://m.media-amazon.com/images/I/61IFoc+u9UL._SX522_.jpg",
      "name": "Walnut - 100gms",
      "packSize": "100 g",
      "price": 175,
      "strikePrice": 239,
      "soldOut": "",
      "notifyme": "",
      "category": "dryFruits",
      "subCatagory": "dryFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "The cashew tree (Anacardium occidentale) is a tropical evergreen tree in the genus Anacardium that produces the cashew seed and the cashew apple accessory .",
      "info": ""
    },
  
    {
      "id": 89,
      "imgUrl": "https://vizagshop.com/wp-content/uploads/2020/08/pinapple-anaspanas-vizag-405x330.jpg",
      "name": "Pineapple",
      "packSize": "800g -1 Kg",
      "price": 107,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "The pineapple (Ananas comosus) is a tropical plant with an edible fruit; it is the most economically significant plant in the family Bromeliaceae.",
      "info": ""
    },
    {
      "id": 90,
      "imgUrl": "https://www.jiomart.com/images/product/600x600/590000508/raw-papaya-500-g-product-images-o590000508-p590000508-0-202207291755.jpg",
      "name": "Papaya Raw",
      "packSize": "1 pc",
      "price": 33,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "(Aprox 600 to 800 g)",
      "benefits": "",
      "description": "Eating raw papaya might benefit the food digestion process. Unripe papaya might contain a good amount of digestive enzyme, which might be an excellent aid to ..",
      "info": ""
    },
    {
      "id": 91,
      "imgUrl": "https://images.healthshots.com/healthshots/en/uploads/2021/09/27184641/pomegranate-1600x900.jpg",
      "name": "Pomegranate (Anar)",
      "packSize": "3 Pcs",
      "price": 145,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "(Aprox 600 to 700 g)",
      "benefits": "",
      "description": "The pomegranate (Punica granatum) is a fruit-bearing deciduous shrub in the family Lythraceae, subfamily Punicoideae, that grows between 5 and 10 m (16 and ...",
      "info": ""
    },
    {
      "id": 92,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/l/10000005-2_1-fresho-apple-royal-gala-economy.jpg",
      "name": "Apple Royal Gala",
      "packSize": "4 pcs",
      "price": 154,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "500-600g",
      "benefits": "",
      "description": "Gala is an apple cultivar with a sweet, mild flavour, a crisp but not hard texture, and a striped or mottled orange or reddish appearance.",
      "info": ""
    },
    {
      "id": 93,
      "imgUrl": "https://e.saravanaonline.com/5688-large_default/fresh-banana-robusta-moreshes-500-gm.jpg",
      "name": "Banana Robusta",
      "packSize": "1 kg",
      "price": 52,
      "strikePrice": "65",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Relish the soft, buttery texture of Robusta bananas that are light green and have a great fragrance and taste. The stalks of Robustas are thick and rigid.",
      "info": ""
    },
    {
      "id": 94,
      "imgUrl": "https://findfresh.in/attachments/shop_images/Orange-Fruit-Pieces-1024x657.jpg",
      "name": "Mosambi (Sweet Lime)",
      "packSize": "1 kg",
      "price": 89,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "The tastiest among the family of citrus fruits is mosambi . Also known as sweet lime, it is a sweet-sour fruit with greenish edible flesh. It has a taste most ...",
      "info": ""
    },
    {
      "id": 95,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0581/2151/9284/products/11_1024x1024.jpg?v=1627403155",
      "name": "Banana Elaichi / Yellaki",
      "packSize": "500 g",
      "price": 75,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": " Elaichi Banana and its Amazing Health Benefits ... Elaichi bananas are smaller in size but they are nutritionally equivalent to regular bananas. ",
      "info": ""
    },
    {
      "id": 96,
      "imgUrl": "https://5.imimg.com/data5/HJ/WF/MY-53341142/chikoo-2f-sapota-2f-sapodilla-500x500.jpg",
      "name": "Chikoo",
      "packSize": "500 g",
      "price": 41,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Manilkara zapota, commonly known as the sapodilla, is a long-lived, evergreen tree native to southern Mexico, Central America and the Caribbean.",
      "info": ""
    },
    {
      "id": 97,
      "imgUrl": "https://post.healthline.com/wp-content/uploads/2020/01/coconut-holding-fruit-1200x628-facebook.jpg",
      "name": "Coconut",
      "packSize": "1 pc",
      "price": 22,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "A coconut is the edible fruit of the coconut palm (Cocos nucifera), a tree of the palm family. Coconut flesh is high in fat and can be dried or eaten fresh or processed into coconut milk or coconut oil. The liquid of the nut, known as coconut water, is used in beverages.",
      "info": ""
    },
    {
      "id": 98,
      "imgUrl": "https://www.healthifyme.com/blog/wp-content/uploads/2020/04/Muskmelon-cover-1.jpg",
      "name": "Musk Melon/ Kharabooja",
      "packSize": "1 pc",
      "price": 83,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "(Aprox 650 to 1200 g)",
      "benefits": "",
      "description": "Muskmelon, also known as Cucumis melo, is a species of melon that belongs to the gourd family. It's closely related to other plants like squash, pumpkin, ...",
      "info": ""
    },
    {
      "id": 99,
      "imgUrl": "https://images.news18.com/ibnlive/uploads/2022/03/watermelon.jpg",
      "name": "Watermelon",
      "packSize": "1 pc",
      "price": 44,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "(Approx 1.5 to 2.7 kg)",
      "benefits": "",
      "description": " Watermelon is around 90% water and also provides electrolytes, such as potassium. This makes it a healthful choice of snack during the hot ...",
      "info": ""
    },
    {
      "id": 100,
      "imgUrl": "https://www.jiomart.com/images/product/original/590001270/pears-green-imported-3-pcs-pack-product-images-o590001270-p590040932-0-202203170454.jpg",
      "name": "Pear Green / Packham",
      "packSize": "500 g",
      "price": 93,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Green pears are a good source of fiber and vitamin C. They improve digestion and help in weight-loss. They fight diabetes and provide anti-oxidants. They are ...",
      "info": ""
    },
    {
      "id": 101,
      "imgUrl": "https://5.imimg.com/data5/LW/VO/MY-31885049/nendran-banana-500x500.jpg",
      "name": "Banana Nendran",
      "packSize": "500 g",
      "price": 68,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Nendran bananas are large and yellow, sweet in flavour with a distinct texture. They are used for the preparation of dishes like thoran, puttu, pazham pori, ...",
      "info": ""
    },
    {
      "id": 102,
      "imgUrl": "https://d1z88p83zuviay.cloudfront.net/ProductVariantThumbnailImages/1364445_425x425.jpg",
      "name": "Orange Imported",
      "packSize": "2 Pcs",
      "price": 40,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Orange Imported 1 kg. Oranges are a favourite snack for many people. They can be eaten out-of-hand or used as a garnish. Besides orange juices, which are ...",
      "info": ""
    },
    {
      "id": 103,
      "imgUrl": "https://m.media-amazon.com/images/I/71Ks4iR+-7L._SL1500_.jpg",
      "name": "Guava White Indian",
      "packSize": "2 Pcs",
      "price": 70,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "(600 - 800g)",
      "benefits": "",
      "description": "White guavas have a sweet-tart, subtly sour, and tropical flavor well suited for fresh and cooked preparations. The fruits are traditionally eaten raw, and the ...",
      "info": ""
    },
    {
      "id": 104,
      "imgUrl": "https://merafarmer.com/132-large_default/raw-banana.jpg",
      "name": "Banana Raw",
      "packSize": "500 g",
      "price": 30,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Raw bananas/ Plantains belong to the banana family but tend to be firmer and cannot be eaten raw. They require cooking and are used when green or under ripe ...",
      "info": ""
    },
    {
      "id": 105,
      "imgUrl": "https://blog-images.pharmeasy.in/2022/06/05130314/25.jpg",
      "name": "Apple Green / Granny Smith",
      "packSize": "4 pcs",
      "price": 140,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Green apples have a pleasing light-green coloured skin with a sweet and sour taste. · They contain more fiber, less carbohydrates and sugar than red apples.",
      "info": ""
    },
    {
      "id": 106,
      "imgUrl": "https://images.medicinenet.com/images/article/main_image/red-banana-benefits.jpg",
      "name": "Banana Red",
      "packSize": "500 g",
      "price": 82,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Red bananas have high quantities of zeaxanthin and lutein. The reddish colour of the red bananas comes from the carotenoid pigments. Lutein and ...",
      "info": ""
    },
    {
      "id": 107,
      "imgUrl": "https://www.jiomart.com/images/product/original/590003564/tender-coconut-cling-wrapped-1-pc-approx-900-g-1300-g-product-images-o590003564-p590003564-0-202203151146.jpg",
      "name": "Coconut Tender / Nariyal Pani",
      "packSize": "1 Pc",
      "price": 71,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Young, fresh and healthy tender coconuts are a pure, tasty and nutritious energy drink that keeps body hydrated round the clock. · Tender coconut is the most ...",
      "info": ""
    },
    {
      "id": 108,
      "imgUrl": "https://cdn.britannica.com/99/143599-050-C3289491/Watermelon.jpg",
      "name": "Special Offer Watermelon",
      "packSize": "1 pc",
      "price": 9,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "1.5 - 2.7 kg",
      "benefits": "",
      "description": "Watermelon contains a variety of nutrients, including potassium, magnesium, and vitamins A and C. · Watermelon is also a rich source of citrulline, an amino acid ..",
      "info": ""
    },
    {
      "id": 109,
      "imgUrl": "https://vizagshop.com/wp-content/uploads/2020/08/Papaya-vizag.jpg",
      "name": "Papaya-Medium",
      "packSize": "900g-1500g",
      "price": 53,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "",
      "benefits": "",
      "description": " Papayas grow in tropical climates and are also known as papaws or pawpaws. Their sweet taste, vibrant color, and the wide variety of health ...",
      "info": ""
    },
    {
      "id": 110,
      "imgUrl": "https://images.hindustantimes.com/rf/image_size_960x540/HT/p2/2019/06/15/Pictures/_3262234e-8f34-11e9-bf7d-e03ff1c1f16f.jpg",
      "name": "Jamun",
      "packSize": "220-250g",
      "price": 224,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": ".",
      "benefits": "",
      "description": " Syzygium cumini, commonly known as Malabar plum, Java plum, black plum, jamun, jaman, jambul, or jambolan, is an evergreen tropical tree in the flowering plant family Myrtaceae, and favored for its fruit, timber, and ornamental value.",
      "info": ""
    },
    {
      "id": 111,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/l/40075384-2_4-fresho-apple-red-delicious-economy.jpg",
      "name": "Apple Red Delicious",
      "packSize": "4 Pc",
      "price": 171,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "freshFruits",
      "tooltipText": "Approx. 500g- 650g",
      "benefits": "",
      "description": "Grapes offer health benefits, primarily due to their high nutrient and antioxidant content. They may benefit the eye, heart, bones, and more.",
      "info": "",
      "tag":"best"
    },
    {
      "id": 112,
      "imgUrl": "https://m.media-amazon.com/images/I/41P8zMQqR7L._SX466_.jpg",
      "name": "Grape Fruit",
      "packSize": "1 Pc",
      "price": 67,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Grapes offer health benefits, primarily due to their high nutrient and antioxidant content. They may benefit the eye, heart, bones, and more.",
      "info": "",
      "tag":"best"
    },
    {
      "id": 113,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0569/9472/6069/products/4_1400x.jpg?v=1655318795",
      "name": "Blueberry",
      "packSize": "1 unit",
      "price": 362,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "(125 g)",
      "benefits": "",
      "description": "Blueberries are a widely distributed and widespread group of perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium.",
      "info": "",
      "tag":"best"
    },
    {
      "id": 114,
      "imgUrl": "https://peppyflora.com/wp-content/uploads/2020/12/Red-Dragon-Fruit-Plant-Pitaya-Peppyflora-Product-01-a-moz.jpg",
      "name": "Dragon Fruit",
      "packSize": "1 pc",
      "price": 118,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Dragon fruits are a widely distributed and widespread group of perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium.",
      "info": ""
    },
    {
      "id": 115,
      "imgUrl": "https://images.news18.com/ibnlive/uploads/2021/09/kiwi-163299398516x9.jpg",
      "name": "Kiwi Green",
      "packSize": "1 unit",
      "price": 103,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "(3 pcs)",
      "benefits": "",
      "description": "Kiwis are high in Vitamin C and dietary fiber and provide a variety of health benefits. This tart fruit can support heart health, digestive health, and immunity.",
      "info": ""
    },
    {
      "id": 116,
      "imgUrl": "https://5.imimg.com/data5/VR/LB/MY-58843567/organic-avocado-250x250.jpg",
      "name": "Avocado Imported",
      "packSize": "1 pc",
      "price": 123,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Avocados are a source of vitamins C, E, K, and B6, as well as riboflavin, niacin, folate, pantothenic acid, magnesium, and potassium. They also provide lutein, ...",
      "info": ""
    },
    {
      "id": 117,
      "imgUrl": "https://4.imimg.com/data4/HP/GL/ANDROID-5323173/product-500x500.jpeg",
      "name": "Kashmir Cherry",
      "packSize": "200g",
      "price": 92,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Fresho Cherry - Kashmir ... Cherries are succulent with a sour-sweet flavour, especially red cherries. As they darken their flavour gets better & the taste ...",
      "info": ""
    },
    {
      "id": 118,
      "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Apricot_and_cross_section.jpg/1280px-Apricot_and_cross_section.jpg",
      "name": "Premium Apricot Shakarpara",
      "packSize": "250g",
      "price": 49,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Apricots are species belonging to Prunus sect. Armeniaca. The taxonomic position of P. brigantina is disputed. It is grouped with plum species according to chloroplast DNA sequences,",
      "info": ""
    },
    {
      "id": 119,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/xxl/40218329_2-fresho-plum-indian.jpg",
      "name": "Plum Indian",
      "packSize": "250g",
      "price": 77,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Indian Plums generally have a maroon- purplish outer skin. The fresh and juicy flavor of the plum makes it energizing fruit to eat.",
      "info": ""
    },
    {
      "id": 120,
      "imgUrl": "https://static.toiimg.com/thumb/64494279.cms?resizemode=4&width=1200",
      "name": "Anjeer (Figs)",
      "packSize": "1 unit",
      "price": 58,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "6-8 Pcs",
      "benefits": "",
      "description": "Agora Figs/Anjeer are rich in fiber and many essential minerals such as magnesium, manganese, calcium, copper, potassium, and vitamins K and B6.",
      "info": ""
    },
    {
      "id": 121,
      "imgUrl": "https://cdn.britannica.com/25/182625-050-327FAC9B/Nectarine-fruits.jpg",
      "name": "Nectarine Indian",
      "packSize": "500g",
      "price": 149,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "nectarine, (Prunus persica), smooth-skinned peach of the rose family (Rosaceae) that is grown throughout the warmer temperate regions of both the Northern ...",
      "info": ""
    },
    {
      "id": 122,
      "imgUrl": "https://cdn2.stylecraze.com/wp-content/uploads/2013/09/2329-18-Best-Benefits-Of-Green-Almonds-For-Skin-Hair-And-Health-is.jpg",
      "name": "Fresh green almond",
      "packSize": "250g",
      "price": 80,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "Fresho green almonds contains healthy fats which helps shed additional fat in the body and keeps you slim. Green almonds also offer protein and fibre and have a ...",
      "info": ""
    },
    {
      "id": 123,
      "imgUrl": "https://5.imimg.com/data5/IP/BO/MY-40565349/litchi-fruit-500x500.jpg",
      "name": "Litchi / Lychee",
      "packSize": "500g",
      "price": 232,
      "strikePrice": "",
      "soldOut": "Sold out for Now",
      "notifyme": "Notify Me",
      "category": "fruits",
      "subCatagory": "exoticFruits",
      "tooltipText": "",
      "benefits": "",
      "description": "lychee, (Litchi chinensis), also spelled litchi or lichi, evergreen tree of the soapberry family (Sapindaceae), grown for its edible fruit. Lychee is native to Southeast Asia and has been a favourite fruit of the Cantonese since ancient times.",
      "info": ""
    },
    {
      "id": 124,
      "imgUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIHYj4wSLn06PjM2_1Vi3c4GNlFsHW_ID1IQ&usqp=CAU",
      "name": "Smoothie Combo (Banana Robusta - 1Kg + Blueberry - 1 Pun...",
      "packSize": "1 unit",
      "price": 418,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "fruitCombos",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 125,
      "imgUrl": "https://storage.googleapis.com/tc46storage/2022/06/3af687c2-mb040.jpg",
      "name": "All fruits combos",
      "packSize": "1 unit",
      "price": 1233,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "fruits",
      "subCatagory": "fruitCombos",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 126,
      "imgUrl": "https://www.jiomart.com/images/product/original/590009517/mango-badami-4-pcs-approx-1200-g-1400-g-product-images-o590009517-p590177428-0-202204070111.jpg",
      "name": "Mango Badami",
      "packSize": "1 kg",
      "price": 122,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "Badami is called Karnataka's Alphonso due to its sweet taste. · It has pale yellow skin with yellowish-orange flesh. · We source premium quality badami mangoes ...",
      "info": ""
    },
    {
      "id": 127,
      "imgUrl": "https://cdn.shopify.com/s/files/1/0556/3986/7580/products/totapuri-mango-500x500_1000x1000.jpg?v=1635943568",
      "name": "Mango Totapuri Raw",
      "packSize": "1 Kg",
      "price": 81,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "The 'Totapuri' mango, or Ginimoothi, is a cultivar that is widely grown in south India and is partially cultivated in Sri Lanka.",
      "info": ""
    },
    {
      "id": 128,
      "imgUrl": "https://m.media-amazon.com/images/I/51h-aJ7RN8L._SL1000_.jpg",
      "name": "Mango Lalbhag Sindhura",
      "packSize": "1 Kg",
      "price": 98,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "",
      "info": ""
    },
    {
      "id": 129,
      "imgUrl": "https://3.imimg.com/data3/JT/TI/MY-2621199/balamani-sindhura-mango-500x500.jpg",
      "name": "Mango suvrna rekha",
      "packSize": "250 g",
      "price": 17,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "Popularly known as Rajgira in Karnataka, the soft and juicy fleshed fruit has a distinct appearance with shades of green and red",
      "info": ""
    },
    {
      "id": 130,
      "imgUrl": "https://img.krishijagran.com/media/48567/kesar-mangoes-source-tradeindia.jpg",
      "name": "Mango Kesar",
      "packSize": "1 kg",
      "price": 135,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "The Kesar Mango is also called as Gir Kesar. It is mostly found in foothills of Girnar, Gujarat. Talala Gir is the largest market of Gir Kesar Mango in ...",
      "info": ""
    },
    {
      "id": 131,
      "imgUrl": "https://www.jiomart.com/images/product/original/590000606/mango-mallika-1-kg-product-images-o590000606-p590334673-0-202201161701.jpg",
      "name": "Mango Mallika",
      "packSize": "1 kg",
      "price": 161,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "Being a hybrid of Neelum and Dasheri, Mallika has a perfect blend of sweetness and tartness. It is a mid season variety. We have handpicked the best quality ...",
      "info": ""
    },
    {
      "id": 132,
      "imgUrl": "https://onlineorganicstore.in/wp-content/uploads/2021/04/Pedda_rasalu_mango_1-1.jpg",
      "name": "Mango rasalu",
      "packSize": "1 kg",
      "price": 155,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "Mostly grown in Nuzived region situated in the Krishna district of Andhra Pradesh, Chinna Rasalu mangoes have an extremely sweet and fibrous pulp.",
      "info": ""
    },
    {
      "id": 133,
      "imgUrl": "https://www.thenewsminute.com/sites/default/files/styles/news_detail/public/Mango1.jpg?itok=RI0kUX3g",
      "name": "Mango banganpalli",
      "packSize": "1 kg",
      "price": 191,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "Banganpalli are sourced from Andhra Pradesh and known for their unique sweet and rich taste. · They are moderately juicy and aromatic with a maize-yellow colour.",
      "info": ""
    },
    {
      "id": 134,
      "imgUrl": "https://5.imimg.com/data5/QG/ZR/WH/SELLER-54848936/neelam-mango-500x500.jpg",
      "name": "Mango neelum",
      "packSize": "1 kg",
      "price": 121,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "mangoes",
      "subCatagory": "mangoes",
      "tooltipText": "",
      "benefits": "",
      "description": "neelum are sourced from Andhra Pradesh and known for their unique sweet and rich taste. · They are moderately juicy and aromatic with a maize-yellow colour.",
      "info": ""
    },
    {
      "id": 135,
      "imgUrl": "https://m.media-amazon.com/images/I/71hFwEGKyZL._SX522_.jpg",
      "name": "Tata sumpunn daal",
      "packSize": "1 kg",
      "price": 121,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "daal",
      "tooltipText": "",
      "benefits": "",
      "description": "Dal is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },
    {
      "id": 136,
      "imgUrl": "https://www.justgotochef.com/img/1522155694-Bikano-Moong%20Dal%20Namkeen-200g-Front%20.jpg",
      "name": "Tata Moong Daal",
      "packSize": "1 kg",
      "price": 141,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "daal",
      "tooltipText": "",
      "benefits": "",
      "description": "Moong Dal is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },

    {
      "id": 137,
      "imgUrl": "https://www.angur.com/wp-content/uploads/2021/09/Masoor-Dal-1-scaled.jpg",
      "name": "Tata Masoor Daal",
      "packSize": "1 kg",
      "price": 141,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "daal",
      "tooltipText": "",
      "benefits": "",
      "description": "Moong Dal is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },
    {
      "id": 138,
      "imgUrl": "https://m.media-amazon.com/images/I/61uTZnkCRcS._SX466_.jpg",
      "name": "Tata Maida",
      "packSize": "500 gms",
      "price": 71,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "atta",
      "tooltipText": "",
      "benefits": "",
      "description": "Maida is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },
    {
      "id": 139,
      "imgUrl": "https://m.media-amazon.com/images/I/91j3Eaf3BZL._SL1500_.jpg",
      "name": "Ashirvad Atta",
      "packSize": "500 gms",
      "price": 41,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "atta",
      "tooltipText": "",
      "benefits": "",
      "description": "Atta is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },{
      "id": 140,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/xxl/124656-2_5-pillsbury-atta-chakki-fresh.jpg",
      "name": "Chakki Fresh Atta",
      "packSize": "500 gms",
      "price": 35,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "atta",
      "tooltipText": "",
      "benefits": "",
      "description": "Atta is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },{
      "id": 141,
      "imgUrl": "https://5.imimg.com/data5/SELLER/Default/2021/9/LQ/QM/DT/20704244/25-kg-bopp-rice-bag-500x500.jpeg",
      "name": "Tiber Rice Bag",
      "packSize": "25 kgs",
      "price": 975,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "Rice",
      "tooltipText": "",
      "benefits": "",
      "description": "Rice is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },{
      "id": 142,
      "imgUrl": "https://bhimavaram.online/image/cache/grocery/GC040-550x550.jpg",
      "name": "Lalitha Brand Rice",
      "packSize": "25 kgs",
      "price": 855,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "rice",
      "tooltipText": "",
      "benefits": "",
      "description": "Rice is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },
    {
      "id": 143,
      "imgUrl": "https://m.media-amazon.com/images/I/41R-wtcQ4zL.jpg",
      "name": "Viru Bhasmathi Rice",
      "packSize": "25 kgs",
      "price": 1855,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "rice",
      "tooltipText": "",
      "benefits": "",
      "description": "Bhasmathi Rice is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    },{
      "id": 144,
      "imgUrl": "https://www.bigbasket.com/media/uploads/p/l/271073-2_3-daawat-basmati-rice-biryani.jpg",
      "name": "Dhawat Brand Bhiryani Rice",
      "packSize": "25 kgs",
      "price": 2055,
      "strikePrice": "",
      "soldOut": "",
      "notifyme": "",
      "category": "kitchenStaples",
      "subCatagory": "rice",
      "tooltipText": "",
      "benefits": "",
      "description": "Bhiryani Rice is a popular side dish in Indian meals. These dishes are made from dried legumes (lentils, beans, or peas) that are split. They are rich in proteins, ...",
      "info": ""
    }
  
  ]
  
  

  module.exports =product